//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("BankAccount", Namespace="", IsNullable=true)]
public partial class BankAccountDto {
    
    private int idField;
    
    private string accountNumberField;
    
    private int ownerIdField;
    
    private float balanceField;
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public int OwnerId {
        get {
            return this.ownerIdField;
        }
        set {
            this.ownerIdField = value;
        }
    }
    
    /// <remarks/>
    public float Balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
}
