//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ComunicationApiXmlDto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banksystem.com/xml")]
    [System.Xml.Serialization.XmlRootAttribute("BankAccountReport", Namespace="http://banksystem.com/xml", IsNullable=true)]
    public partial class BankAccountReportDto {
        
        private System.DateTime timeOfReportCreationField;
        
        private float currentAccountBalanceField;
        
        private float previousAccountBalanceField;
        
        private string ownerNameField;
        
        private string ownerSurnameField;
        
        private string ownerEmailField;
        
        /// <remarks/>
        public System.DateTime TimeOfReportCreation {
            get {
                return this.timeOfReportCreationField;
            }
            set {
                this.timeOfReportCreationField = value;
            }
        }
        
        /// <remarks/>
        public float CurrentAccountBalance {
            get {
                return this.currentAccountBalanceField;
            }
            set {
                this.currentAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public float PreviousAccountBalance {
            get {
                return this.previousAccountBalanceField;
            }
            set {
                this.previousAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerSurname {
            get {
                return this.ownerSurnameField;
            }
            set {
                this.ownerSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerEmail {
            get {
                return this.ownerEmailField;
            }
            set {
                this.ownerEmailField = value;
            }
        }
    }
}
