//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ComunicationApiXmlDto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banksystem.com/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://banksystem.com/xml", IsNullable=false)]
    public enum CreationAccountOwnerFlags {
        
        /// <remarks/>
        EMPTY = 1,
        
        /// <remarks/>
        SUCCESS = 2,
        
        /// <remarks/>
        INCORRECT_NAME = 4,
        
        /// <remarks/>
        INCORRECT_SURNAME = 8,
        
        /// <remarks/>
        INCORRECT_EMAIL = 16,
        
        /// <remarks/>
        INCORRECT_PASSWORD = 32,
    }
}
