//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ComunicationApiXmlDto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banksystem.com/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://banksystem.com/xml", IsNullable=true)]
    public partial class CreationAccountOwnerResponse {
        
        private CreationAccountOwnerFlags creationFlagsField;
        
        private AccountOwnerDto accountOwnerField;
        
        /// <remarks/>
        public CreationAccountOwnerFlags CreationFlags {
            get {
                return this.creationFlagsField;
            }
            set {
                this.creationFlagsField = value;
            }
        }
        
        /// <remarks/>
        public AccountOwnerDto AccountOwner {
            get {
                return this.accountOwnerField;
            }
            set {
                this.accountOwnerField = value;
            }
        }
    }
}
