//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ComunicationApiXmlDto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banksystem.com/xml")]
    [System.Xml.Serialization.XmlRootAttribute("CurrenciesPurchaseSellRate", Namespace="http://banksystem.com/xml", IsNullable=true)]
    public partial class CurrenciesPurchaseSellRateDto {
        
        private float purchaseEuroField;
        
        private float sellEuroField;
        
        private float purchaseUsdField;
        
        private float sellUsdField;
        
        private float purchaseGbpField;
        
        private float sellGbpField;
        
        private float purchaseChfField;
        
        private float sellChfField;
        
        /// <remarks/>
        public float PurchaseEuro {
            get {
                return this.purchaseEuroField;
            }
            set {
                this.purchaseEuroField = value;
            }
        }
        
        /// <remarks/>
        public float SellEuro {
            get {
                return this.sellEuroField;
            }
            set {
                this.sellEuroField = value;
            }
        }
        
        /// <remarks/>
        public float PurchaseUsd {
            get {
                return this.purchaseUsdField;
            }
            set {
                this.purchaseUsdField = value;
            }
        }
        
        /// <remarks/>
        public float SellUsd {
            get {
                return this.sellUsdField;
            }
            set {
                this.sellUsdField = value;
            }
        }
        
        /// <remarks/>
        public float PurchaseGbp {
            get {
                return this.purchaseGbpField;
            }
            set {
                this.purchaseGbpField = value;
            }
        }
        
        /// <remarks/>
        public float SellGbp {
            get {
                return this.sellGbpField;
            }
            set {
                this.sellGbpField = value;
            }
        }
        
        /// <remarks/>
        public float PurchaseChf {
            get {
                return this.purchaseChfField;
            }
            set {
                this.purchaseChfField = value;
            }
        }
        
        /// <remarks/>
        public float SellChf {
            get {
                return this.sellChfField;
            }
            set {
                this.sellChfField = value;
            }
        }
    }
}
