//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class TransferData {
    
    private string sourceAccountNumberField;
    
    private string targetAccountNumberField;
    
    private float amountField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string SourceAccountNumber {
        get {
            return this.sourceAccountNumberField;
        }
        set {
            this.sourceAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string TargetAccountNumber {
        get {
            return this.targetAccountNumberField;
        }
        set {
            this.targetAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    public float Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}
