//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ComunicationApiXmlDto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banksystem.com/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://banksystem.com/xml", IsNullable=false)]
    public enum TransferResultCodes {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        OWNER_ACCOUNT_DOESNT_EXISTS,
        
        /// <remarks/>
        TARGET_BANK_ACCOUNT_DOESNT_EXISTS,
        
        /// <remarks/>
        INSUFICIENT_BANK_ACCOUNT_FUNDS,
        
        /// <remarks/>
        TIMEOUT,
        
        /// <remarks/>
        TRANSFER_HAS_BEEN_INTERUPTED,
    }
}
